# Generated by Django 4.1.3 on 2022-11-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_comentarios_active_comentarios_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='post_id',
            new_name='post',
        ),
    ]
