# Generated by Django 4.1.3 on 2022-11-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_rename_post_id_comentarios_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='post',
            new_name='post_id',
        ),
    ]
