# Generated by Django 4.1.3 on 2022-11-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_rename_post_comentarios_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='post_id',
            new_name='post',
        ),
    ]
