# Generated by Django 4.1.3 on 2022-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_rename_post_id_comentarios_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
