# Generated by Django 4.1.3 on 2022-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_comentarios_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
