# Generated by Django 4.1.3 on 2022-12-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
