# Generated by Django 4.1.3 on 2022-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='Posts.categoria'),
        ),
    ]
