# Generated by Django 4.1.3 on 2022-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_categoria_post_destacado_post_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='title',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ManyToManyField(to='Posts.autor'),
        ),
    ]
