# Generated by Django 4.1.3 on 2022-12-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0014_autor_rename_title_categoria_categoria_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='Autor',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='title',
        ),
    ]
